package com.example.favoritemovies

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
data class Movie(
    val title: String,
    val plot: String,
    val poster: String,
    val year: Int,
    val genres: ArrayList<String>,
    val language: String,
    val rating: Double,
    val rated: String,
    val runtime: Int,
    val director: String,
    val actors: ArrayList<String>,
) : Parcelable

val listMovie = arrayListOf(
    Movie(
        "Interstellar",
        "Earth's future has been riddled by disasters, famines, and droughts. There is only one way to ensure mankind's survival: Interstellar travel. A newly discovered wormhole in the far reaches of our solar system allows a team of astronauts to go where no man has gone before, a planet that may have the right environment to sustain human life.",
        "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
        2014,
        arrayListOf("Adventure", "Drama", "Sci-Fi"),
        "English",
        4.3,
        "PG-13",
        169,
        "Christopher Nolan",
        arrayListOf("Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"),
    ),
    Movie(
        "Ant-Man and the Wasp: Quantumania",
        "Scott Lang and Hope Van Dyne, along with Hank Pym and Janet Van Dyne, explore the Quantum Realm, where they interact with strange creatures and embark on an adventure that goes beyond the limits of what they thought was possible.",
        "https://m.media-amazon.com/images/M/MV5BMDIzM2FlNTctNjAzZi00YzhkLThjYWQtMDY5Njc0NjdmMGVlXkEyXkFqcGdeQXVyMTUzOTcyODA5._V1_SX300.jpg",
        2023,
        arrayListOf("Action", "Adventure", "Comedy"),
        "English",
        4.0,
        "PG-13",
        125,
        "Peyton Reed",
        arrayListOf("Paul Rudd", "Evangeline Lilly", "Jonathan Majors"),
    ),
    Movie(
        "Everything Everywhere All at Once",
        "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes and connecting with the lives she could have led.",
        "https://m.media-amazon.com/images/M/MV5BYTdiOTIyZTQtNmQ1OS00NjZlLWIyMTgtYzk5Y2M3ZDVmMDk1XkEyXkFqcGdeQXVyMTAzMDg4NzU0._V1_SX300.jpg",
        2022,
        arrayListOf("Action", "Adventure", "Comedy"),
        "English",
        4.0,
        "R",
        139,
        "Dan Kwan",
        arrayListOf("Michelle Yeoh", "Stephanie Hsu", "Jamie Lee Curtis"),
    ),
    Movie(
        "The Menu",
        "A young couple travels to a remote island to eat at an exclusive restaurant where the chef has prepared a lavish menu, with some shocking surprises.",
        "https://m.media-amazon.com/images/M/MV5BMzdjNjI5MmYtODhiNS00NTcyLWEzZmUtYzVmODM5YzExNDE3XkEyXkFqcGdeQXVyMTAyMjQ3NzQ1._V1_SX300.jpg",
        2022,
        arrayListOf("Horror", "Thriller"),
        "English",
        3.6,
        "R",
        107,
        "Mark Mylod",
        arrayListOf("Ralph Fiennes", "Anya Taylor-Joy", "Nicholas Hoult"),
    ),
    Movie(
        "M3GAN",
        "A robotics engineer at a toy company builds a life-like doll that begins to take on a life of its own.",
        "https://m.media-amazon.com/images/M/MV5BMDk4MTdhYzEtODk3OS00ZDBjLWFhNTQtMDI2ODdjNzQzZTA3XkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_SX300.jpg",
        2022,
        arrayListOf("Horror", "Sci-Fi", "Thriller"),
        "English",
        3.25,
        "PG-13",
        102,
        "Gerard Johnstone",
        arrayListOf("Allison Williams", "Violet McGraw", "Ronny Chieng"),
    ),
    Movie(
        "Glass Onion",
        "Famed Southern detective Benoit Blanc travels to Greece for his latest case.",
        "https://m.media-amazon.com/images/M/MV5BYmZlZDZkZjYtNzE5Mi00ODFhLTk2OTgtZWVmODBiZTI4NGFiXkEyXkFqcGdeQXVyMTE5MTg5NDIw._V1_SX300.jpg",
        2022,
        arrayListOf("Comedy", "Crime", "Drama"),
        "English",
        3.6,
        "PG-13",
        139,
        "Rian Johnson",
        arrayListOf("Daniel Craig", "Edward Norton", "Kate Hudson"),
    ),
    Movie(
        "Titanic",
        "84 years later, a 100 year-old woman named Rose DeWitt Bukater tells the story to her granddaughter Lizzy Calvert, Brock Lovett, Lewis Bodine, Bobby Buell and Anatoly Mikailavich on the Keldysh about her life set in April 10th 1912, on a ship called Titanic when young Rose boards the departing ship with the upper-class passengers and her mother, Ruth DeWitt Bukater, and her fiancé, Caledon Hockley. Meanwhile, a drifter and artist named Jack Dawson and his best friend Fabrizio De Rossi win third-class tickets to the ship in a game. And she explains the whole story from departure until the death of Titanic on its first and last voyage April 15th, 1912 at 2:20 in the morning.",
        "https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDQtY2E5My00ZTliLWIzOTUtMTY4ZGI1YjdiNjk3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg",
        1997,
        arrayListOf("Drama", "Romance"),
        "English",
        3.95,
        "PG-13",
        194,
        "James Cameron",
        arrayListOf("Leonardo DiCaprio", "Kate Winslet", "Billy Zane"),
    ),
    Movie(
        "Avengers: Endgame",
        "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos's actions and undo the chaos to the universe, no matter what consequences may be in store, and no matter who they face...",
        "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_SX300.jpg",
        2019,
        arrayListOf("Action", "Adventure", "Drama"),
        "English",
        4.2,
        "PG-13",
        181,
        "Anthony Russo",
        arrayListOf("Robert Downey Jr.", "Chris Evans", "Mark Ruffalo"),
    ),
    Movie(
        "Annihilation",
        "A biologist signs up for a dangerous, secret expedition into a mysterious zone where the laws of nature don't apply.",
        "https://m.media-amazon.com/images/M/MV5BMTk2Mjc2NzYxNl5BMl5BanBnXkFtZTgwMTA2OTA1NDM@._V1_SX300.jpg",
        2018,
        arrayListOf("Adventure", "Drama", "Horror"),
        "English",
        3.4,
        "R",
        115,
        "Alex Garland",
        arrayListOf("Natalie Portman", "Jennifer Jason Leigh", "Tessa Thompson"),
    ),
    Movie(
        "Call Me by Your Name",
        "In 1980s Italy, romance blossoms between a seventeen-year-old student and the older man hired as his father's research assistant.",
        "https://m.media-amazon.com/images/M/MV5BNDk3NTEwNjc0MV5BMl5BanBnXkFtZTgwNzYxNTMwMzI@._V1_SX300.jpg",
        2017,
        arrayListOf("Drama", "Romance"),
        "English",
        3.9,
        "R",
        132,
        "Luca Guadagnino",
        arrayListOf("Timothée Chalamet", "Armie Hammer", "Michael Stuhlbarg"),
    ),
    Movie(
        "Doctor Strange in the Multiverse of Madness",
        "Doctor Strange teams up with a mysterious teenage girl from his dreams who can travel across multiverses, to battle multiple threats, including other-universe versions of himself, which threaten to wipe out millions across the mul...",
        "https://m.media-amazon.com/images/M/MV5BNWM0ZGJlMzMtZmYwMi00NzI3LTgzMzMtNjMzNjliNDRmZmFlXkEyXkFqcGdeQXVyMTM1MTE1NDMx._V1_SX300.jpg",
        2022,
        arrayListOf("Action", "Adventure", "Fantasy"),
        "English",
        3.45,
        "PG-13",
        126,
        "Sam Raimi",
        arrayListOf("Benedict Cumberbatch", "Elizabeth Olsen", "Chiwetel Ejiofor"),
    ),
    Movie(
        "Minority Report",
        "In a future where a special police unit is able to arrest murderers before they commit their crimes, an officer from that unit is himself accused of a future murder.",
        "https://m.media-amazon.com/images/M/MV5BZTI3YzZjZjEtMDdjOC00OWVjLTk0YmYtYzI2MGMwZjFiMzBlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
        2002,
        arrayListOf("Action", "Crime", "Mystery"),
        "English",
        3.8,
        "PG-13",
        145,
        "Steven Spielberg",
        arrayListOf("Tom Cruise", "Colin Farrell", "Samantha Morton"),
    ),
    Movie(
        "Lucy",
        "A woman, accidentally caught in a dark deal, turns the tables on her captors and transforms into a merciless warrior evolved beyond human logic.",
        "https://m.media-amazon.com/images/M/MV5BODcxMzY3ODY1NF5BMl5BanBnXkFtZTgwNzg1NDY4MTE@._V1_SX300.jpg",
        2014,
        arrayListOf("Action", "Sci-Fi", "Thriller"),
        "English",
        3.2,
        "R",
        89,
        "Luc Besson",
        arrayListOf("Scarlett Johansson", "Morgan Freeman", "Choi Min-sik"),
    ),
)